version: '3.8'

services:

  pgsql_app:
    container_name: 'pgsql_app'
    image: postgres:13.3
    ports:
      - "5433:5432"
    env_file:
      .env
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    restart: unless-stopped

  app_keycloak:
    container_name: 'app_keycloak'
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/project
    command: python src/main.py

  pgsql_keycloak:
    container_name: 'pgsql_keycloak'
    image: postgres:13.3
    ports:
      - "5434:5432"
    env_file:
      .env.keycloak
    volumes:
      - pgsql_keycloak_data:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak:
    container_name: 'keycloak'
    image: quay.io/keycloak/keycloak:23.0.6
    ports:
      - "8080:8080"
    env_file:
     .env.keycloak
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: [ "start-dev" ]


volumes:
  pgsql_data:
  pgsql_keycloak_data:
  keycloak_data:
